const feedTypes = {
  FETCH_POSTS_START: 'FETCH_POSTS',
  FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',
  FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
  ADD_POST: 'ADD_POST',
};

export default feedTypes;
