const postsTypes = {
  FETCH_POST_DETAILS_START: 'FETCH_POST_DETAILS_START',
  FETCH_POST_DETAILS_FAILURE: 'FETCH_POST_DETAILS_FAILURE',
  FETCH_POST_DETAILS_SUCCESS: 'FETCH_POST_DETAILS_SUCCESS',
  SET_POST_COMMENTS: 'SET_POST_COMMENTS',
  SET_BOOKMARKED: 'SET_BOOKMARKED',
  ADD_POSTS: 'ADD_POSTS',
  VOTE_POST: 'VOTE_POST',
  VOTE_COMMENT: 'VOTE_COMMENT',
  ADD_COMMENT: 'ADD_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',
  SET_REPLY_COMMENT: 'SET_REPLY_COMMENT',
  CLEAR_REPLY_COMMENT: 'CLEAR_REPLY_COMMENT',
  SET_COMMENT_REPLIES: 'SET_COMMENT_REPLIES',
  ADD_COMMENT_REPLY: 'ADD_COMMENT_REPLY',
  TOGGLE_SHOW_COMMENTS: 'TOGGLE_SHOW_COMMENTS',
  CLEAR_POSTS: 'CLEAR_POSTS',
  TOGGLE_BOOKMARK: 'TOGGLE_BOOKMARK'
};

export default postsTypes;
