const postsTypes = {
  FETCH_POST_COMMENTS_START: 'FETCH_POST_COMMENTS_START',
  FETCH_POST_COMMENTS_FAILURE: 'FETCH_POST_COMMENTS_FAILURE',
  FETCH_POST_COMMENTS_SUCCESS: 'FETCH_POST_COMMENTS_SUCCESS',
  ADD_POSTS: 'ADD_POSTS',
  LIKE_POST: 'LIKE_POST',
  ADD_COMMENT: 'ADD_COMMENT',
  SET_REPLY_ID: 'SET_REPLY_ID',
  CLEAR_REPLY_ID: 'CLEAR_REPLY_ID'
};

export default postsTypes;
