const postsTypes = {
  FETCH_POST_COMMENTS_START: 'FETCH_POST_COMMENTS_START',
  FETCH_POST_COMMENTS_FAILURE: 'FETCH_POST_COMMENTS_FAILURE',
  FETCH_POST_COMMENTS_SUCCESS: 'FETCH_POST_COMMENTS_SUCCESS',
  ADD_POSTS: 'ADD_POSTS',
  LIKE_POST: 'LIKE_POST',
  ADD_COMMENT: 'ADD_COMMENT',
  SET_REPLY_COMMENT: 'SET_REPLY_COMMENT',
  CLEAR_REPLY_COMMENT: 'CLEAR_REPLY_COMMENT',
  SET_COMMENT_REPLIES: 'SET_COMMENT_REPLIES',
  ADD_COMMENT_REPLY: 'ADD_COMMENT_REPLY',
  TOGGLE_SHOW_COMMENTS: 'TOGGLE_SHOW_COMMENTS'
};

export default postsTypes;
