const currentProfileTypes = {
  FETCH_PROFILE_START: 'FETCH_PROFILE_START',
  FETCH_PROFILE_FAILURE: 'FETCH_PROFILE_FAILURE',
  FETCH_PROFILE_SUCCESS: 'FETCH_PROFILE_SUCCESS',
  LIKE_POST: 'LIKE_POST'
};

export default currentProfileTypes;
