const userTypes = {
  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_OUT: 'SIGN_OUT',
  BOOKMARK_POST: 'BOOKMARK_POST'
};

export default userTypes;
